### PR TITLE
Convert dateTime to CE(S)T dateTime

### LINKED ISSUE #38: Convert datetime to CE(S)T timezone
There are some reports report date is incorrect for stock bought around midnight CET i.e. on Asian or Australian exchanges. Need to take a look if we should/can do timezone translation in that case to match the exact time to CET date.

### PR DESCRIPTION
**Pull request by ddbk**
Another year has passed and we have a couple of new issues to solve (and features to add) to make our lives a little easier in February. 😅

This is a quick and dirty way to handle events happening in different timezones, since IB report uses US/Eastern as a default timezone for outputting `dateTime` values but FURS wants us to report events as they happen in Slovenian local time. This PR closes #38.

I'm leaving this in draft for now since it's not fully tested yet and I'll try to make some improvements working with dates if I find some time. Otherwise we can still merge as it is and iterate later.

### CODE REVIEW

**Comment by jamsix** [comment]
Hm ... one of the script users asked FURS about TZ and this was their answer:

> Spoštovani. Vezano na vaše pisno vprašanje kateri datum navedete na napovedi zaradi časovne razlike, vas obveščamo, da navedete čas, ki je naveden na poročilu posrednika. 

Sounds a bit ambiguous but on the other hand the only sensible interpretation here is that you use the date used in broker's report, which in our case would be EST?

**Comment by ddbk** [comment]
Lol, that's funny. 😂 By FURS' logic you could potentially sell something before you buy it (but still do a long trade!) - buy on e.g. Saxo (CET time), sell the same security immediately after that on IB (EST time). But it really seems that's the interpretation they gave in their response... 🤷‍♂️ Should we close this PR then?

**Comment by ddbk** [comment]
Let's close this one without merging (if others agree) because of the FURS answer above. I'll try to get another response/confirmation from them, and re-open if needed.

**Comment by jamsix** [comment]
Appears not to be needed by FURS.

**Pull request closed without merging**
