### PR TITLE
Add support for stock splits

### PR DESCRIPTION
**Pull request by brinkokevin**

### CODE REVIEW

**Comment by pronebird** [comment]
Awesome! How about parsing stock splits from the IBKR output, they have various corporate actions including splits and reverse splits reported, should be relatively easy to parse them out and build a dictionary, then do what you do.

**Comment by brinkokevin** [comment]
> Awesome! Could it please pick up stock splits from corporate actions in XML output from IBKR?

Was actually just working on that. 

I also noticed that it didn't properly adjust the price I missed the part where it adjusted tradePrice because of the multiplier. and used price from xml instead of trades dictionary where multiplier adjusted price is.
image

**Comment by pronebird** [comment]
Great! If that helps that's how reverse split looks like. Each `CorporateAction` has a `type`, it's `RS` for reverse split.

```
<CorporateActions>
	<CorporateAction accountId="U304XXXX" acctAlias="" model="" currency="USD" fxRateToBase="1" assetCategory="STK" symbol="UAN" description="UAN(US1266331065) SPLIT 1 FOR 10 (UAN, CVR PARTNERS LP, US1266332055)" conid="454386216" securityID="US1266332055" securityIDType="ISIN" cusip="126633205" isin="US1266332055" listingExchange="NYSE" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20201124" dateTime="20201123;202500" actionDescription="UAN(US1266331065) SPLIT 1 FOR 10 (UAN, CVR PARTNERS LP, US1266332055)" amount="0" proceeds="0" value="0" quantity="50" fifoPnlRealized="0" mtmPnl="0" code="" type="RS" transactionID="XXXX" levelOfDetail="DETAIL" />
	<CorporateAction accountId="U304XXXX" acctAlias="" model="" currency="USD" fxRateToBase="1" assetCategory="STK" symbol="UAN.OLD" description="UAN(US1266331065) SPLIT 1 FOR 10 (UAN.OLD, CVR PARTNERS LP, US1266331065)" conid="86631284" securityID="US1266331065" securityIDType="ISIN" cusip="126633106" isin="US1266331065" listingExchange="NYSE" underlyingConid="" underlyingSymbol="" underlyingSecurityID="" underlyingListingExchange="" issuer="" multiplier="1" strike="" expiry="" putCall="" principalAdjustFactor="" reportDate="20201124" dateTime="20201123;202500" actionDescription="UAN(US1266331065) SPLIT 1 FOR 10 (UAN.OLD, CVR PARTNERS LP, US1266331065)" amount="0" proceeds="0" value="0" quantity="-500" fifoPnlRealized="0" mtmPnl="0" code="" type="RS" transactionID="XXXX" levelOfDetail="DETAIL" />
</CorporateActions>
```

**Comment by brinkokevin** [comment]
> Great! If that helps that's how reverse split looks like. Each `CorporateAction` has a `type`, it's `RS` for reverse split.
Why are there two? This comit should handle reverse splits as well https://github.com/jamsix/ib-edavki/pull/16/commits/4885bced7250ad80d59eefa6f6faf784baba6e4f let me know if there is an issue.

**Comment by pronebird** [comment]
@brinkokevin yeah that's weird. It looks like they retired the old Security ID in their database and just added a new one. `conid` is different and the only thing that connects the dots is the first part of description, i.e: `UAN(US1266331065)`

**Comment by brinkokevin** [comment]
Just fixed the multiplier, should work for reverse splits now.

**Comment by pronebird** [comment]
@brinkokevin thanks! Alright let me re-export my reports with corporate actions and see what it does. :)

**Comment by pronebird** [comment]
@brinkokevin amazing! Great work man! Worked for my 1 for 10 split. Just ran a diff against my old `KDVP.xml`:

Screen Shot 2021-01-17 at 12 27 52

**Comment by brinkokevin** [comment]
> P.S.: maybe update `README.md` and update instructions ("Izvoz poročila v platformi InteractiveBrokers") to select "Corporate actions", options: Detail, columns: Select all.

That is already updated.

**Comment by jamsix** [comment]
Amazing work @brinkokevin.
@pronebird I don't have any stock splits in my portfolio, based on yours are you OK with merging this?

**Comment by pronebird** [comment]
@jamsix yes. The PR looks fine and works on my data set.

**Pull request merged**
